const mongoose = require("mongoose");
const Schema = mongoose.Schema;
const Types = Schema.Types;

// foreign key into resources collection, requires schema
// const resourceSchema = require("./resource");

const librarySchema = new Schema({
    // _id is auto-generated by MongoDB, and is our primary key
    name: { type: Types.String, trim: true, required: true, unique: true },
    owner: { type: Types.String, trim: true, required: true, unique: true }, // 1 owner per library
    resources: [{ type: Types.ObjectId, ref: "resource" }], // array of foreign keys into resources collection
})

module.exports = mongoose.model("librarie", librarySchema);